### ISSUE TITLE
parser-icu does not handle HTML tags

### ISSUE THREAD

**Issue by pboguslawski** [sveltekit-i18n/lib#104]
Using HTML tags in translations makes parser-icu throw

```
500

INVALID_TAG

SyntaxError: INVALID_TAG
    at Function.parse [as __parse] (/@fs/tmp/lib/node_modules/@formatjs/icu-messageformat-parser/lib/index.js:31:21)
    at new IntlMessageFormat (/@fs/tmp/lib/node_modules/intl-messageformat/lib/src/core.js:136:42)
    at Object.parse (/@fs/tmp/lib/node_modules/@sveltekit-i18n/parser-icu/dist/index.js:1:154)
    at O (/@fs/tmp/lib/node_modules/@sveltekit-i18n/base/dist/index.js:1:1261)
    at /@fs/tmp/lib/node_modules/@sveltekit-i18n/base/dist/index.js:1:4065
    at index.svelte:21:10
    at Object.$$render (/@fs/tmp/lib/node_modules/svelte/internal/index.mjs:1770:22)
    at Object.default (root.svelte:43:39)
    at eval (/src/routes/__layout.svelte:29:41)
    at Object.$$render (/@fs/tmp/lib/node_modules/svelte/internal/index.mjs:1770:22)

```
To repoduce: setup example as described on https://github.com/sveltekit-i18n/lib/tree/master/examples/parser-icu  and change 

```
"plural": "You have {value, plural, =0 {no photos.} =1 {one photo.} other {# photos.}}",
```
to

```
"plural": "<a href=\"https://example.com/\">You</a> have {value, plural, =0 {no photos.} =1 {one photo.} other {# photos.}}",
```
in `src/lib/translations/en/content.json` and change

```
<p>{$t('content.plural', { value: $number })}</p>
```
to
```
<p>{@html $t('content.plural', { value: $number })}</p>
```
in `src/routes/index.svelte`.

**Comment by pboguslawski** [comment]
Works fine [when quoted](https://github.com/willdurand/BazingaJsTranslationBundle/issues/310) like this:

```
"plural": "'<a href=\"https://example.com/\">'You'</a>' have {value, plural, =0 {no photos.} =1 {one photo.} other {# photos.}}",
```
