### ISSUE TITLE
ICU parser example not work

### ISSUE THREAD

**Issue by druid8** [sveltekit-i18n/lib#82]
ICU parser example is not building (dev works).
`npm run build` fails with: `SyntaxError: Named export 'IntlMessageFormat' not found. The requested module 'intl-messageformat' is a CommonJS module, which may not support all module.exports as named exports. `

Full output:
```
druid@knieja:~/Pulpit/tmp/lib/examples/parser-icu$ npm run build

> parser-icu@0.0.1 build
> svelte-kit build

vite v2.9.13 building for production...
✓ 36 modules transformed.
  Client build completed. Wrote 9 chunks and 1 assets
  Building server
.svelte-kit/output/client/_app/immutable/manifest.json                       2.00 KiB
.svelte-kit/output/client/_app/immutable/pages/__layout.svelte-1146874d.js   2.18 KiB / gzip: 1.13 KiB
.svelte-kit/output/client/_app/immutable/error.svelte-8c29fdbe.js            1.56 KiB / gzip: 0.75 KiB
.svelte-kit/output/client/_app/immutable/pages/index.svelte-006300e9.js      2.88 KiB / gzip: 1.35 KiB
.svelte-kit/output/client/_app/immutable/chunks/preload-helper-beb8b45d.js   1.34 KiB / gzip: 0.81 KiB
.svelte-kit/output/client/_app/immutable/start-cb19f3d3.js                   22.30 KiB / gzip: 8.35 KiB
.svelte-kit/output/client/_app/immutable/chunks/content-03638256.js          0.48 KiB / gzip: 0.29 KiB
.svelte-kit/output/client/_app/immutable/chunks/index-eb7ba480.js            7.60 KiB / gzip: 3.09 KiB
.svelte-kit/output/client/_app/immutable/chunks/content-5d443e23.js          0.46 KiB / gzip: 0.29 KiB
.svelte-kit/output/client/_app/immutable/chunks/index-02ba6100.js            47.28 KiB / gzip: 14.33 KiB
vite v2.9.13 building SSR bundle for production...
✓ 17 modules transformed.
Generated an empty chunk: "hooks"
.svelte-kit/output/server/manifest.json                       1.68 KiB
.svelte-kit/output/server/index.js                            72.74 KiB
.svelte-kit/output/server/entries/pages/__layout.svelte.js    1.02 KiB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js   0.72 KiB
.svelte-kit/output/server/entries/pages/index.svelte.js       1.74 KiB
.svelte-kit/output/server/chunks/index-2580c06c.js            3.42 KiB
.svelte-kit/output/server/chunks/index-8da469ab.js            13.23 KiB
.svelte-kit/output/server/chunks/hooks-1c45ba0b.js            0.00 KiB
.svelte-kit/output/server/chunks/content-03638256.js          0.55 KiB
.svelte-kit/output/server/chunks/content-5d443e23.js          0.53 KiB
  Prerendering
file:///home/druid/Pulpit/tmp/lib/examples/parser-icu/node_modules/@sveltekit-i18n/parser-icu/dist/index.js:1
import{IntlMessageFormat as p}from"intl-messageformat";var f=e=>({parse:(r,[t,o],a,n)=>r===void 0?`${n}`:new p(r,a,o,e).format(t)}),u=f;export{u as default};
       ^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'IntlMessageFormat' not found. The requested module 'intl-messageformat' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'intl-messageformat';
const {IntlMessageFormat: p}from"intl-messageformat";var f=e=>({parse:(r,[t,o],a,n)=>r===void 0?`${n}`:new p(r,a,o,e).format(t)}),u=f;export{u: default} = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:127:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:191:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:331:24)
    at async Promise.all (index 0)
    at async respond$1 (file:///home/druid/Pulpit/tmp/lib/examples/parser-icu/.svelte-kit/output/server/index.js:1751:13)
    at async resolve (file:///home/druid/Pulpit/tmp/lib/examples/parser-icu/.svelte-kit/output/server/index.js:2140:105)
    at async respond (file:///home/druid/Pulpit/tmp/lib/examples/parser-icu/.svelte-kit/output/server/index.js:2095:22)
    at async visit (file:///home/druid/Pulpit/tmp/lib/examples/parser-icu/node_modules/@sveltejs/kit/dist/vite.js:1121:20)
SyntaxError: Named export 'IntlMessageFormat' not found. The requested module 'intl-messageformat' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'intl-messageformat';
const {IntlMessageFormat: p}from"intl-messageformat";var f=e=>({parse:(r,[t,o],a,n)=>r===void 0?`${n}`:new p(r,a,o,e).format(t)}),u=f;export{u: default} = pkg;

[vite-plugin-svelte-kit] 500 /
> 500 /
    at file:///home/druid/Pulpit/tmp/lib/examples/parser-icu/node_modules/@sveltejs/kit/dist/vite.js:1020:11
    at save (file:///home/druid/Pulpit/tmp/lib/examples/parser-icu/node_modules/@sveltejs/kit/dist/vite.js:1239:4)
    at visit (file:///home/druid/Pulpit/tmp/lib/examples/parser-icu/node_modules/@sveltejs/kit/dist/vite.js:1130:3)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Steps to reproduce:
1) follow instrunctions from readme (clone, cd to `./parser-icu`), install latest `sveltekit-i18n/base`
2) run `npm run build` to make a production build

npm: 8.1.2
node: v17.1.0
vite: 2.9.13
typescript: 4.6.4
tslib: 2.4.0
svelte: 3.48.0
sveltejs/kit: 1.0.0-next.355

**Comment by jarda-svoboda** [comment]
Well, this is weird... In case i try to locally link the `parser-icu` dependency using `npm link @sveltekit-i18n/parser-icu`, the `dev`, `build` and `preview` works normally...🤔

**Comment by jarda-svoboda** [comment]
OK, [fixed](https://github.com/sveltekit-i18n/lib/commit/ed932f9888ebac8edcd698f510a904962b6d542b)...
You should include
```js
{
  ssr: {
    noExternal: true, // or ['@sveltekit-i18n/*', 'intl-messageformat', '@formatjs/*']
  }
}
```

in your `vite.config.js`. The example now works as expected...
